### DISCUSSION TITLE
NTP time

### DISCUSSION THREAD

**Discussion by proasnet** [fredlcore/BSB-LAN#607] [General]
As I saw in the configuration file, NTP is only available for ESP so far. I will patiently wait for it to be available for DUE as well, it will be an interesting feature if it is able to correct and set this time correctly even with a different time in the boiler. For example, if the NTP time differs from the boiler time by 1-2 minutes, it will make an automatic adjustment in the boiler.

**Comment by fredlcore** [comment]
Unfortunately, it is not at all likely that this will be implemented for the Arduino Due because the library that we use for the ESP32 is not compatible with the Arduino Due. And even if there is a different library, it would probably not be too easy because NTP always returns time in UTC, i.e. without timezone as well as daylight savings information. This is all included in the ESP32 library. So unless you want to run your boiler in UTC, I don't see a chance to have NTP on the Due. It's probably easier to write a little script for BSB_LAN_custom.h that polls a website with the correct, timezone- and daylight-saving-adjusted time and then use that to set BSB-LAN's time as well as the heater's. However, this has to come from a contributor, I won't have the time to work on that.

**Comment by proasnet** [comment]
Hello @fredlcore 
I solved the BAXI boiler time synchronization with BSBLAN by automating it in HA, which at 4 o'clock in the morning sends an MQTT command to set the time, regardless of the deviation. It also takes into account the time shift, because HA has NTP time in it.

```
alias: Time sync BAXI
description: At 4:00:00 set time as 4:00
trigger:
  - platform: time
    at: "04:00:00"
condition: []
action:
  - service: mqtt.publish
    data:
      topic: BSB-LAN
      payload_template: S1=4:0:0
mode: single
```

Its working easy.
