### DISCUSSION TITLE
[Home Assistant] How to publish sensor value to MQTT as BSB-LAN topic

### DISCUSSION THREAD

**Discussion by benoit-cty** [fredlcore/BSB-LAN#692] [Q&A]
Hello,

I have a new installation of BSB-LAN ( [v4.1](https://github.com/fredlcore/BSB-LAN/releases/tag/v4.1)).

My climat integration is working but I'd like to set my own measured room temperature and disconnect the Navilink A59.

Here is my automation, thanks to https://community.home-assistant.io/t/bsb-lan-integration/113501/176 :

```
- id: "1734257760544"
  alias: PAC - Publish Sensor Value to MQTT as BSB-LAN topic
  description: ""
  triggers:
    - trigger: time_pattern
      minutes: "/5"
  conditions: []
  actions:
    - action: mqtt.publish
      metadata: {}
      data:
        evaluate_payload: false
        qos: 0
        retain: false
        payload: I10000={{ states('sensor.ble_temperature_a4c138657746') }}
        topic: BSB-LAN
  mode: single
```

And what I saw in MQTT Explorer:
![image](https://github.com/user-attachments/assets/37a2a7ca-2501-4531-8377-4fbc05c9ded5)

And the climate that works:

```
- name: "Pompe à chaleur"
  payload_on: 1
  payload_off: 0
  modes:
    - auto
    - heat
    - cool
    - "off"
  mode_state_topic: "BSB-LAN/0/12/700/status"
  mode_state_template: >-
    {% set values = { '0 - Mode protection':'off', '1 - Automatique':'auto', '2 - Réduit':'cool', '3 - Confort':'heat'} %}
    {{ values[value] if value in values.keys() else 'off' }}
  mode_command_topic: "BSB-LAN"
  mode_command_template: >-
    {% set values = { 'off':'S700=0', 'auto':'S700=1', 'cool':'S700=2', 'heat':'S700=3'} %}
    {{ values[value] if value in values.keys() else '0' }}
  current_temperature_topic: "BSB-LAN/0/39/8740/status"
  min_temp: 12
  max_temp: 19
  temp_step: 0.5
  temperature_state_topic: "BSB-LAN/0/12/710/status"
  temperature_command_topic: "BSB-LAN"
  temperature_command_template: "{{'S710='+ (value| string)}}"
```

Thanks for your help.

**Comment by fredlcore** [comment]
So just to be sure, that's not a question, but a solution on how to send the current temperature from a HA sensor to BSB-LAN, right? In that case, thanks a lot :)!

**Comment by benoit-cty** [comment]
No, sorry, the `climate` is working fine to set the target temperature and display the temperature coming from `8740`.

But the 8740 is fixed to the last value send by the Navilink (even if I remove the battery from it), never the value send to `I10000`, so my question is "How to send the value of an HA sensor to the heater ?"

I have 50% in "750 Circuit de chauffe 1 - Influence de la température ambiante" as stated in the documentation [Send-room-temperature-to-heater](https://github.com/fredlcore/BSB-LAN/wiki/Send-room-temperature-to-heater)

I can see in MQTT explorer that the temperature is send to `BSB-LAN/I10000` every 5 minutes.

**Comment by fredlcore** [comment]
Hm, what I know is that the parameters changed by BSB-LAN are sometimes not reflected on the display unit, because the Navilink system seems to route everything via the display unit, so the display unit does not actively query the current value from the heater each time it is displayed (as other display units from Siemens do).
Do you check the value of 8740 on the heater of via BSB-LAN? On the heater, it's possible that the changes are not reflected. But if you send /I10000=19.5 it should reflect if you query parameter 8740 in BSB-LAN (or whatever the parameter is that is supposed to show the current room temperature).
You can check if the room temperature is actually having an effect on the heater by sending a temperature 2-3 degrees lower than the setpoint temperature. Then the heater should start. Likewiese, it should stop if the temperature is 2-3 degrees higher then the setpoint. If that all works, then the temperature has to be stored somewhere where it can be queried via BSB-LAN.

**Comment by benoit-cty** [comment]
Thanks for your quick answer, I did not manage to set temperature with `mqtt.publish` but it works with a curl command. 🎉 

Here is how to do it :

In `configuration.yaml` create a curl command line with your sensor value :

```yaml
shell_command:
  pac_set_room_temp: "curl http://bsb-lan.local/I10000={{ states('sensor.ble_temperature_a4c138657746') }}"
```
(replace `ble_temperature_a4c138657746` by your temperature sensor)

In `automation.yaml` create an automation to call this command every 5 minutes:

```yaml
- id: '1734257760544'
  alias: PAC - Publish Sensor Value to BSB-LAN
  description: ''
  triggers:
  - trigger: time_pattern
    minutes: /5
  conditions: []
  actions:
  - action: shell_command.pac_set_room_temp
    data: {}
  mode: single
```

I have removed the batteries of the Navilink to avoid interference.
