### ISSUE TITLE
[FEATURE REQUEST] Publish MQTT update on SET commands

### ISSUE THREAD

**Issue by fl42** [fredlcore/BSB-LAN#409]
Hello,

**Is your feature request related to a problem? Please describe.**
When updating a parameter (e.g., changing parameter 701 using HTTP), systems that rely on MQTT (e.g., Home Assistant) don't have immediate update about the new state (they have to wait up to log_interval).

**Describe the solution you'd like**
I think it makes sense to publish a MQTT update before the next scheduled update (defined by log_interval) if a SET command was issued (i.e., a command that may change the value of a parameter).

**Describe alternatives you've considered**
Reduce log interval parameter.

**Describe your own contribution**
I had a look to the code but I'm not sure what is the best way to implement it.
Setting lastMQTTTime to 0 when a SET command is issued is one option.

**Additional context**
Thanks for your great work!

**Comment by fredlcore** [comment]
@thorbennehmer or @Luposoft63, would this be doable?

**Comment by Luposoft63** [comment]
I think this is doable.
@fl42 But, why don't you use the set command via MQTT? With it you have the inbuilt answer via MQTT. This were the best way for all.
If we change 'lastMQTTTime' for this event  I'm not shure wether other user get any problems...

**Comment by fl42** [comment]
Hello @Luposoft63 @fredlcore 

Thanks for your quick answer,

Let me detail my use case: I'm using Home Assistant (HA) to control my heater using BSB LAN.
My sensors in HA are [MQTT sensors](https://www.home-assistant.io/integrations/sensor.mqtt/) and I'm interacting with BSB LAN using REST queries.

```yaml
sensor:
  - platform: mqtt
    state_topic: "bsb_lan/json"
    name: Status circuit 1
    value_template: >
      {% if '8000' in value_json['BSB-LAN']['status'] %}
        {{ value_json['BSB-LAN']['status']['8000'] }}
      {% else %}
        {{ states('sensor.status_circuit_1') }}
      {% endif %}

rest_command:
  set_comfort_mode:
    url: http://IP/S701=2
```

When I'm calling the service `set_comfort_mode` (i.e. calling the URL `http://IP/S701=2`), my interface in HA that shows the sensor "Status circuit 1" is not updated immediately.

Basically the MQTT instead of publishing every log_interval will publish an update every [min_interval, log_interval] where min_interval is an interval to avoid being flooded if the user is doing multiple updates in a short period (e.g., 1s)

Or even just an URL to trigger a MQTT update would be fine too, if it's easier to implement.
A call to `http://IP/MQTT` would publish immediately a MQTT update.
This approach does not change how MQTT behaves, but adds a new feature..

Is the need clearer? :)
