### ISSUE TITLE
[BUG] MQTT DHW push button, publish "BSB-LAN/10019=1" not working

### ISSUE THREAD

**Issue by proasnet** [fredlcore/BSB-LAN#537]
**Before submitting a bug report, please make sure that you have checked [chapter 14](https://1coderookie.github.io/BSB-LPB-LAN_EN/chap14.html) of the manual** ("Problems and their Possible Causes"). Most problems that are reported to us can be solved by going through the solutions provided there.

**BSB-LAN Version**
3.0.4-20221222224441

**Architecture**
Arduino Due

**Bus system**
BSB

**Describe the bug**
MQTT problem for DHW push

**To Reproduce**
1. Publish BSB-LAN/S10019=1

In Saturday, I upgraded BSB-LAN from 3.0.1 to 3.0.4 for try DHW push, and in URL
ip-adress/S10019=1 DHW push working.
I am trying this over MQTT pusblish in my HA, and in this situation push not working.

I have this code for button

in my configuration.yaml, I call file
`mqtt: !include mqtt_sensors.yaml`
Its okay, other mqtt entities working.
and in file mqtt_sensors.yaml
```
button:
  - name: DHW push
    unique_id: bsb_lan_dhw_push
    availability_topic: "BSB-LAN/status"
    command_topic: "BSB-LAN"
    command_template: >
     "S10019=1"
```
or I am trying another version
```
button:
  - name: DHW push
    unique_id: bsb_lan_dhw_push
    availability_topic: "BSB-LAN/status"
    command_topic: "BSB-LAN/S10019=1"
```

Not working the first or the second variant.

Its possible, that problem is on my side, in yaml code

**Comment by proasnet** [comment]
![obrázok](https://user-images.githubusercontent.com/76579362/213973718-ce3a7802-af88-4d54-a46a-96f2de67969e.png)
![obrázok](https://user-images.githubusercontent.com/76579362/213973800-6e57c6fd-9547-42e8-94a5-1d70f12a785a.png)

**Comment by proasnet** [comment]
```
button:
  - name: DHW push
    unique_id: bsb_lan_dhw_push
    availability_topic: "BSB-LAN/status"
    command_topic: "BSB-LAN"
    payload_press: "S10019=1"
    qos: 0
    retain: false
```
Working... Issue on my config.
