### ISSUE TITLE
[FEATURE REQUEST] MQTT topic structure without category in path (optional?)

### ISSUE THREAD

**Issue by uschindler** [fredlcore/BSB-LAN#680]
Hi,
I did not yet install the new version of BSB-LAN but reviewed the changes since the Git version of end October that's still installed locally.

The new Topic structure with the endpoints `/status`, `/set`, `/inf`,.. looks fine and makes it much easier to set values from Home Assistant (HASS), as you no longer need templates to form the message to set a value, it should work automagically. `/poll` is also great because I can setup a cronjob in Homeassistant to poll specific values with different intervals (normaly things like heater status and temperature are fetched 40 seconds for me, but stuff like actual heating curve due to adaption do not need to be fetched that often). So I can change this to send `/poll` MQTT messages with different intervals. Thats wonderful!

In addition communicating with the BSB-LAN only through the MQTT serializes the messages "in order". Sending messages in parallel through HTTP sometimes leads to crushes (TCP reset) as the BSB-LAN is single-threaded. When everything from HASS goes through MQTT all arrives at BSB-LAN in order in a single "thread".

But one thing annoys me: The new topic structure contains the category id, which is somehow redundant. The device ID is easy to handle with search/replace in the config of HASS. But category id is totally useless! It may be usefull for autodiscovery, but if you don't use auto-discovery and configure your entities by hand (I have about 20 including a climate control entity and water heater entity), it gets annoying to lookup all category ids which are different for different devices. This also makes it hard to post reuseable configurations, because the categories are different in each system, while the parameter numbers are reuseable and the same for most heaters (for common parameters like temperature, FA status,....).

Would it be possible to either revert addition of category id to MQTT messages or provide a compile time config which removes them from the string formatting when creating MQTT topic paths?

Once there is an easy option to remove them, I will upgrade and report back how the new endpoints work (`/poll, /set, /status, /inf`).

**Comment by fredlcore** [comment]
That's the thing if you introduce new features - some people want it this way, some people want it that way. The argument to filter MQTT-subscribed parameters based on categories rather than having to enter parameters one-by-one was the reason I introduced that feature. To me, this is a more frequent use case than re-using configurations across different systems. If the systems are really the same, the category IDs will also be the same. If they are not, I wouldn't want to encourage people re-using configurations in the first place as you may or may not know what you are doing. And the "may nots" are the ones who cause support-time ;). If it is any consolation, the category ID is ignored when setting parameters, so you can write to BSB-LAN/1/0/700 in order to write to parameter 700 on device ID 1.

**Comment by uschindler** [comment]
I don't agree with the "filtering". If you want to filter you filter by parameter id. They are all pre-structured. You know that 7xx is the Heizkreis 1, so its easy to filter them by path in MQTT explorers. I know almost all of my parameter IDs (I knew them already before using BSB-LAN).
I am just mentioning this. I would agree if the categories are "user-readable" strings, but just the IDs makes discovery not more useful.

I know from the code that while setting the values it does not matter, but the bigger problem is setting up entities where you wait for changes on "/status", they need to have the correct category ID.

**Comment by fredlcore** [comment]
Well, heating circuit 1 is more than just parameter numbers 7xx, they go up to 900. And if you know the parameter IDs, you will probably also know the order of the categories and thus also the category IDs (at least in systems with just one heating system). If you are interested in the parameters of HC1, it's of course much faster to subscribe just to BSB-LAN/0/XX/ instead of subscribing to each parameter manually. 

User-readable strings would also not solve the problem of portability, because they would be localized. 
And a compile time flag would also not help in terms of portability, as users would have to know that any configuration they see on the internet would only work with this or that setting. And you won't believe how many e-mails I get where people complain about the one error message that is the first one explained in the "troubleshooting" section - which again only can come up if you haven't read the quickstart instructions properly. So I cannot introduce any features that bring in more ambiguity.

In any case, it's a one-time task, and since reading/monitoring - i.e. subscribing - parameters are the majority compared to those that you want to actively change regularly (maybe a handful?), the advantages of the present model are clear to me. 

But I'll leave this issue open for a while. Let's see if there are more users who feel that this is a step back.

**Comment by fredlcore** [comment]
Ok, since it only affects two lines in code, I have now added the NO_MQTT_HIERARCHY compile option, which you can set using `#define NO_MQTT_HIERARCHY` in `BSB_LAN_config.h`. I won't advertise this feature for the above-mentioned reasons, so please do not post configurations that make use of this to a wider audience, as it will for sure increase my support load. Of course, if you can adjust your templates to work with the "standard" configuration, this is, of course, welcome.

**Comment by uschindler** [comment]
OK thanks for this.

Actually this setting only helps for the `/status` case, because it again makes the structure inconsistent. So I agree that it is a support desaster.

I will try to update my code on the weekend and extract the category ID. Maybe you can subscribe to topics like "/BSB-LAN/0/#/712" instead (not sure if that works with HASS), when writing you could use "0" as suggested before..

**Comment by uschindler** [comment]
See https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/ for how to use wildcards.

**Comment by uschindler** [comment]
Looks like you can use topics for subscribing in HASS: https://community.home-assistant.io/t/mqtt-topic-wildcard/389382/3

This makes it easy to ignore the category when subscribing for updates. For setting/informing you can use "0" and for polling the topic ID is enough.

**Comment by fredlcore** [comment]
I missed one instance, so now it should have a consistent structure without the category ID. Can you test again?
And yes, such kind of subscriptions should be doable if you want to ignore the category ID on the level of MQTT subscription. Wouldn't that solve you problem even better?

**Comment by uschindler** [comment]
> I missed one instance, so now it should have a consistent structure without the category ID. Can you test again? And yes, such kind of subscriptions should be doable if you want to ignore the category ID on the level of MQTT subscription. Wouldn't that solve you problem even better?

Yes and no. For subscribing wildcards are a good idea, but for setting values you still need a special case. But as "0" as category works for setting values I am fine with that limitation.

**Comment by uschindler** [comment]
I will give both variants a try later, I am a bit busy at moment.

**Comment by fredlcore** [comment]
So then I could/should revert the changes? If it means that you can create relocatable templates with the way you just described, then I'd rather remove it. If you'd still need the "flat" hierarchy, I'll keep it, with the risk that people will try it out and clog their MQTT topic hierarchy ;)...

**Comment by fredlcore** [comment]
Ok, thanks!

**Comment by uschindler** [comment]
Hi, I tried to test it but after upgrading (before, all was working correct), it is unable to detect the BSB. I cleared the EPROM manually, still no success. It seems to get the correct device/type and variant, but it reports 0 and 0 for both. Therefore I can't get it online at all.

```
19:23:07.638 -> Bus devices found:
19:23:07.638 -> 128/97/100/
19:23:07.638 -> Device family: 0
19:23:07.638 -> Device variant: 0
19:23:10.621 -> Start network services
19:23:10.621 -> Starting MDNS service with hostname BSB-LAN
19:23:10.621 -> Update Server started on port 8080.
19:23:10.621 -> Setup complete
19:23:10.621 -> Connecting to MQTT broker sirius.home on port 1883...
19:23:10.621 -> Client ID: BSB-LAN
19:23:10.678 -> Will topic: BSB-LAN/status
19:23:10.678 -> Connected to MQTT broker, updating will topic
19:23:10.678 -> Subscribed to topic 'BSB-LAN/#'
19:23:10.678 -> Published status 'online' to topic 'BSB-LAN/status'
19:23:38.497 -> MQTT connection lost
19:23:48.494 -> Connecting to MQTT broker sirius.home on port 1883...
19:23:48.494 -> Client ID: BSB-LAN
19:23:48.494 -> Will topic: BSB-LAN/status
19:23:48.494 -> Connected to MQTT broker, updating will topic
19:23:48.494 -> Subscribed to topic 'BSB-LAN/#'
19:23:48.494 -> Published status 'online' to topic 'BSB-LAN/status'
19:23:51.044 -> 60002 Ping!
19:23:51.044 -> Device family: 0
19:23:51.044 -> Device variant: 0
```

This repeats forever. Can you help. Unfortunately theres no way anymore to set family and variant anymore.

It shows correct in first line: 97/100 but then reports 0/0
```
19:23:07.638 -> Bus devices found:
19:23:07.638 -> 128/97/100/
19:23:07.638 -> Device family: 0
19:23:07.638 -> Device variant: 0
```

Uwe

**Comment by uschindler** [comment]
I found the issue. The following line breaks everything in the logic. After disabling it, all works:
https://github.com/fredlcore/BSB-LAN/blob/2796578ca42d259f1a25893ca08d85b4efe19fbc/BSB_LAN/BSB_LAN.ino#L4057

This line of code changes the bus type for no reason to LBP which then breaks. On Web interface it also shows LBP on the config page.

So basically I got the master version running, now trying to configure MQTT! Should I open another issue about the logic problem setting to bus type LBP on discovery of bus devices?

**Comment by uschindler** [comment]
There are more problems in the code. It boots up successfully, but every request for a parameter (via auto-logging or MQTT) leads to:

```
20:15:29.694 -> GET /K0!128 HTTP/1.1
20:15:29.769 -> 0 - Uhrzeit
20:15:32.912 -> DC C2 80 0B 06 3D 05 00 0B 68 58 
20:15:32.912 ->  query failed
20:15:35.980 -> DC C2 80 0B 06 3D 05 00 0B 68 58 
20:15:35.980 ->  query failed
20:15:39.069 -> DC C2 80 0B 06 3D 05 00 0B 68 58 
20:15:39.109 ->  query failed
```

I think I will revert to latest published version....

**Comment by uschindler** [comment]
OK, released version 4.1 boots and works correct. As it did not have the newest MQTT topic structure (with status,....), I then tried several commits and found out that e66083da838581e9fb9a95c90fff8d08d032c0ef works for me.

If you want to fix the issues with discovery and startup (and possibly those where the query fails. It looks like the new code somehow mixes up device numbers and serial numbers. The newest version with the bug (after it started with commenting out the code as described above) reported device ID 128 in MQTT messages, while the working e66083da838581e9fb9a95c90fff8d08d032c0ef reports ID 0.

Some issues I also found while upgrading: If I did not delete all retained messages with `mosquitto_sub -u home -P lolifu --remove-retained -t 'BSB-LAN/#'` before startup, trhe code crashed with a stack overflow after complainig that it received messages vom mosquito with wrong syntax.

I will now try to use commit e66083da838581e9fb9a95c90fff8d08d032c0ef with wildcard topics in HASS.

**Comment by uschindler** [comment]
Hi,
with wildcard topics it works fine. The most complex example is the "climate" entity with many settings:

```
climate:
  - name: Heizkreis
    unique_id: bsb-lan.heating
    availability_topic: "BSB-LAN/status"
    precision: 0.1

    action_topic: "BSB-LAN/0/+/8000/status"
    action_template: >
      {% set idx = value.split() | first | int %}
      {{ 'heating' if idx in [111,113,114,116,137,155] else 'idle' }}

    modes: [ "auto", "off" ]
    mode_state_topic: "BSB-LAN/0/+/700/status"
    mode_state_template: >
      {% set idx = value.split() | first | int %}
      {{ 'off' if idx == 0 else 'auto' }}
    mode_command_topic: "BSB-LAN/0/0/700/set"
    mode_command_template: >
      {{ '0' if value=='off' else states('sensor.heizkreis_letzte_non_off_betriebsart') | default('1') }}

    preset_modes: [ "Schutzbetrieb", "Automatik", "Reduziert", "Komfort" ]
    preset_mode_state_topic: "BSB-LAN/0/+/700/status"
    preset_mode_value_template: >
      {% set mapping = {0: 'Schutzbetrieb', 1: 'Automatik', 2: 'Reduziert', 3: 'Komfort'} %}
      {% set idx = value.split() | first | int %}
      {{ mapping[idx] }}
    preset_mode_command_topic: "BSB-LAN/0/0/700/set"
    preset_mode_command_template: >
      {% set mapping = {'Schutzbetrieb': 0, 'Automatik': 1, 'Reduziert': 2, 'Komfort': 3} %}
      {{ mapping[value] }}

    current_temperature_topic: "BSB-LAN/0/+/10000/status"
    temperature_command_topic: "BSB-LAN/0/0/710/set"
    temperature_state_topic: "BSB-LAN/0/+/710/status"
    temp_step: 0.1
    max_temp: 35
    min_temp: 10
    qos: 1
```

Please note for the on/off button it uses the last known state (another entity) which is not "Frostschutz".

**Basically I think you can revert the two changesets.** With wildcards it is not needed. The topics are still a bit async but much better than explicitly giving the category ids.

For getting a value it uses wildcard, for setting the fixed category=0:

```
    temperature_command_topic: "BSB-LAN/0/0/710/set"
    temperature_state_topic: "BSB-LAN/0/+/710/status"
```

The cool thing is: For getting/setting temperature, no template is needed, as the payload can be directly sent.

I will only improve my config to have a global variable for the device ID reused.
